export const APPLICATION_ACCOUNT_DATA_SIZE = 72;
export const COLLECTION_ACCOUNT_DATA_SIZE = 105;
export const COLLECTION_ATTRIBUTE_ACCOUNT_DATA_SIZE = 138;
export const COLLECTION_INSTRUCTION_ACCOUNT_DATA_SIZE = 105;
export const COLLECTION_INSTRUCTION_ARGUMENT_ACCOUNT_DATA_SIZE = 137;
