export const APPLICATION_DATA_SIZE = 72;
export const COLLECTION_DATA_SIZE = 105;
export const COLLECTION_ATTRIBUTE_DATA_SIZE = 138;
export const COLLECTION_INSTRUCTION_DATA_SIZE = 105;
export const COLLECTION_INSTRUCTION_ARGUMENT_DATA_SIZE = 137;
export const COLLECTION_INSTRUCTION_ACCOUNT_DATA_SIZE = 138;
export const COLLECTION_INSTRUCTION_ACCOUNT_BOOL_ATTRIBUTE_DATA_SIZE = 106;
